#!/bin/bash
# baklite - increases or decreases backlight

path="/sys/devices/backlight.20/backlight/backlight.20/brightness"
min=1

if [ "$#" -gt "1" ]; then
	echo "usage: $0 [+/- brightness]" 1>&2
fi


if [ "$#" -eq "0" ]; then
	cat $path
	exit 1
fi

if [ "$(($(cat $path) + $1))" -gt "255" ]; then
	echo 255 > $path
	echo "255 is max" 1>&2
	exit
elif [ "$(($(cat $path) + $1))" -lt "$min" ]; then
	echo $min > $path
	echo "$min is min" 1>&2
	exit
else
	echo $(($(cat $path) + $1)) > $path
fi	
