#!/bin/bash
# co - mounts monk@$ip home directory to my desktop

#error checking and set up
if [ $# -eq 0 ]; then
	echo "usage: $0 username"
	exit 1
fi

# make sure there is ip to connect to
if [ -s $ip ]; then
	echo variable ip is empty 
	exit 1
fi


for i in $*; do
	user="$i"
	mount="$HOME/Desktop/mnt_$user"
	# make sure mount point is good
	if [ -d $mount ]; then 
		echo "mount point already exists"
		exit 1
	else
		mkdir $mount
		echo connecting....
		sshfs $user@$ip:/home/$user $mount 2> /dev/null	
	fi

	# if failed to connect, exit
	if [ $? -ne 0 ]; then
	rmdir $mount
	echo "sshfs failed"
	exit 1
fi
done


