#!/bin/bash
# dco - disconnect the mount point

# assuming all mounts go onto the Desktop
mountpoint="$HOME/Desktop"

# if no arguments, just umount everything
regex='^mnt'
if [ $# -eq 0 ]; then
	for i in $mountpoint/*; do
		if [[ `basename $i` =~ $regex ]]; then
			umount $i && rmdir $i
		fi
	done
fi

for i in $*; do
	mount="$mountpoint/mnt_$i"
	umount $mount && rmdir $mount
done

