#!/bin/bash
#fig - open random jpeg from a directory (for figure drawing) 
# has timed options!

pick_photo () {
	PHOTO=`cat $FILE | sort -R | head -1`
	echo "open $PHOTO"

	open $PHOTO
}

create_directory () {
	echo "creating $FILE"
	find . | grep '\.jpg' > $FILE
	exit 0
}



FILE=_directory.txt
if [ "$1" = '-c' ]; then
	create_directory
fi


if [ "$1" = '-r' ]; then
	a=1
	for i in *.jpg *.JPG; do
	  new=$(printf "%04d.jpg" "$a") #04 pad to length of 4
	  mv -i -- "$i" "$new"
	  let a=a+1
	done
	create_directory
fi


# checking if _directory.txt exists
# saves some work as well as a good double check
if ! [[ -s "$FILE" ]]; then
    echo "ERROR: $FILE doesn't exist, use -c option to generate" >&2
    exit 1
fi

# if a number is inputted, then it's a timed loop
if [ $# -eq 0 ]; then
	pick_photo
else
	# checking if number
	re='^[0-9]+$'
	if ! [[ $1 =~ $re ]] ; then
   		echo "ERROR: not a number" >&2
   		exit 1
	fi

	# less than 10 seconds too fast
	if [ $1 -le 10 ] ; then
   		echo "ERROR: please pick number bigger than 10" >&2
   		exit 1
	fi

	SEC=$1
	echo "looping every $SEC seconds"

	while true; do
		pick_photo
		sleep $SEC
	done
fi



