#!/bin/bash

ip link set wlan0 down
if [ ! -d /run/systemd/reolve ]; then
	mkdir /run/systemd/resolve
	if [ ! -r /run/systemd/resolve/resolve.conf ]; then
		cp /etc/resolv.conf.bak /run/systemd/resolve/resolv.conf
	fi
fi
wifi-menu
